export const Socket_Event = Object.freeze({
  OPEN: "open",
  LEAVE_ROOM: "leaveRoom",
  JOIN_ROOM: "joinRoom",
  LEAVE: "leave",
  NOTIFY: "notify",
  READ_MESSAGE: "readMessage",
  READED_MESSAGE: "readedMessage",
  READ_ALL_NOTIFICATION: "readAllNotification",
  READED_ALL_NOTIFICATION: "readedAllNotification",
  NOTIFICATION: "notification",
  RECEIVE_NOTIFICATION: "receiveNotification",
  RECEIVE_MESSAGE: "receiveMessage",
  UPDATE_MESSAGE: "updateMessage",
  ONLINE: "online",
  OFFLINE: "offline",
  ERROR: "socketError",
  DELETE_MESSAGE: "deleteMessage",
  TYPING_MESSAGE: "typingMessage",
  TYPING_END: "typingEnd",
  DELETE_ROOM: "deleteRoom",
  UPDATE_ROOM: "updateRoom",
  CREATE_ROOM: "createRoom",
  VISIT_ROOM: "visitRoom",
  UNVISIT_ROOM: "unvisitRoom",
  USER_TYPING: "userTyping",
  USER_TYPING_END: "userTypingEnd",
  COUNT_MESSAGE: "countMessage",
  GET_MESSAGE_COUNT: "getMessageCount",
  COUNT_NOTIFICATION: "countNotification",
  GET_NOTIFICATION_COUNT: "getNotificationCount",
  READ_NOTIFICATION: "readNotification",
  READED_NOTIFICATION: "readedNotification",
});
type ValueOf<T> = T[keyof T];
export type SOCKETEVENT = ValueOf<typeof Socket_Event>;
