export const Socket_Event = Object.freeze({
  OPEN: "open",
  LEAVE_ROOM: "leaveRoom",
  JOIN_ROOM: "joinRoom",
  LEAVE: "leave",
  NOTIFY: "notify",
  READ_MESSAGE: "readMessage",
  READED_MESSAGE: "readedMessage",
  NOTIFICATION: "notification",
  RECEIVE_NOTIFICATION: "receiveNotification",
  RECEIVE_MESSAGE: "receiveMessage",
  UPDATE_MESSAGE: "updateMessage",
  ONLINE: "online",
  OFFLINE: "offline",
  ERROR: "socketError",
  DELETE_MESSAGE: "deleteMessage",
  TYPING_MESSAGE: "typingMessage",
  TYPING_END: "typingEnd",
  DELETE_ROOM: "deleteRoom",
  UPDATE_ROOM: "updateRoom",
  ADD_PARTICIPANTS: "addParticipants",
  UPDATE_PARTICIPANTS: "updateParticipants",
  DELETE_PARTICIPANTS: "deleteParticipants",
  RECEIVE_GAR: "receiveGar",
  DELETE_GAR: "deleteGar",
  REJECT_GAR: "rejectGar",
  APPROVE_GAR: "approveGar",
  CREATE_ROOM: "createRoom",
  VISIT_ROOM: "visitRoom",
  UNVISIT_ROOM: "unvisitRoom",
  USER_TYPING: "userTyping",
  USER_TYPING_END: "userTypingEnd",
});
type ValueOf<T> = T[keyof T];
export type SOCKETEVENT = ValueOf<typeof Socket_Event>;
